<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="www/main.css">
  <title>Accueil</title>
</head>

<body>
  <?php require "templates/header.phtml" ?>
  <div class="images">
    <!-- <h1 class="h1_Welcome">Welcome to the <span class="bigApple">big</span> city</h1> -->
    <h1 class="h1_Welcome">Welcome to you <span class="bigApple"><?= $user ?> !</span></h1>
  </div>

  <section class="section1">

    <h2 class="h2_nyc">↓ Exercice n°1 ci-dessous ↓</h2>


    <div class="channel">
      <p class="p_channel">Contenu du tableau $channel</p>
      <p><?= print_r($channel) ?></p>
    </div>

    <?php foreach ($channel as $key => $value) : ?>
      <p class="p_channel"><?= $key ?></p>
      <?php if ($key == 'horlogerie') : ?>

        <?php foreach ($value as $x) : ?>
          <p class="p_channel2"><?= $x ?></p>
        <?php endforeach; ?>

      <?php endif; ?>

    <?php endforeach; ?>


  </section>


  <?php require "templates/footer.phtml" ?>
  <script src="script/main.js"></script>
</body>

</html>