<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="www/footer.css">
  <title>Footer</title>
</head>

<body>
  <footer class="footer_container">
    <!-- <h1 class="h1_footer">Nous contacter</h1> -->
    <p>@copyright 2022 Alexandre Braga</p>
  </footer>
</body>

</html>