<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="www/header.css">
  <title>Header</title>
</head>

<body>
  <!-- Par convention les pages "include" prennent un "_" en début de nom -->
  <header>
    <div class="header_container">
      <nav class="navbar_container">
        <ul class="liste_nav_bar">
          <li class="items_nav_bara">
            <a href="index.php" class="a_nav">Accueil</a>
          </li>
          <li class="items_nav_bara">
            <a href="convertisseur.php" class="a_nav">Convertisseur</a>
          </li>
          <li class="items_nav_bara">
            <a href="convertisseur2.php" class="a_nav">Convertisseur 2</a>
          </li>
          <li class="items_nav_bara">
            <a href="inscription.php" class="a_nav">Inscription</a>
          </li>
          <li class="items_nav_bara">
            <a href="conn_success.php" class="a_nav">Connexion</a>
          </li>
        </ul>
      </nav>
    </div>

  </header>
</body>

</html>