<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="www/main.css">
  <title>Inscription</title>
</head>

<body>
  <?php require "templates/header.phtml" ?>
  <form action="inscription.php" method="post">
    <p><?= $demande ?></p>

    <label for="firstname">Prénom</label>
    <input type="text" class="" id="firstname" name="firstname">

    <label for="name">Nom</label>
    <input type="text" class="" id="name" name="name">

    <label for="email">E-mail</label>
    <input type="text" class="" id="email" name="email">

    <div class="check_box_container">
      <label for="majeur">Êtes-vous majeur ?</label>
      <div class="majeur">
        <label for="majeur">Oui</label>
        <input class="inradio" type="radio" name="majeur" value="Oui" id="oui">
        <label for="majeur">Non</label>
        <input class="inradio" type="radio" name="majeur" value="Non" id="non">
      </div>
    </div>


    <button class="btn shine" type="submit">Valider</button>
  </form>






  <?php require "templates/footer.phtml" ?>
  <script src="script/main.js"></script>
</body>

</html>